import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.sass'
import Header from '@/components/Header/Header'
// import New, { DemoCarousel } from '@/components/New'
import Form from '@/components/Form/Form'
import ChacraForm from '@/components/Form/ChacraForm'
import Container from '../components/Container/Container'
import Hero from '@/components/Hero/Hero'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <Hero/>
        {/* <New /> */}
        <ChacraForm />
        {/* <Form /> */}
        <h2>Startseite</h2>
        {/* <DemoCarousel/> */}
      </main>
    </>
  )
}
